export const IS_LOADING = 'IS_LOADING';
export const GET_GALLERIES_SUCCESS = 'GET_GALLERY_SUCCESS';
export const GET_GALLERIES_FAILED = 'GET_GALLERY_FAILED';

export const IS_LOADING_ARTS = 'IS_LOADING_ARTS';
export const GET_ARTS_SUCCESS = 'GET_ARTS_SUCCESS';
export const GET_ARTS_FAILED = 'GET_GALLERY_FAILED';
export const DELETE_ART = 'DELETE_ART_SUCCESS';
